[package]
name = "xtitc"
version = "0.1.0"
authors = ["Samuel Adams <samuel.adams.d@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"
fixed = "1.7"
csv = "1.1"
rand = "0.4.2"