class_label_count = 2
attribute_count = 12
instance_count = 248
tree_count = 90
max_depth = 8
feature_count = 10
epsilon = 0.01
decimal_precision = 10
data = "clear_pain/1X_train.csv"
classes = "clear_pain/1y_train.csv"
data_test = "clear_pain/1X_test.csv"
classes_test = "clear_pain/1y_test.csv"
seed = 0
emulate_fpp = false
discretize_per_node = true